### ISSUE TITLE
quickstart fails for self managed worker nodes

### ISSUE THREAD

**Issue by ankitm123** [jx3-gitops-repositories/jx3-eks-terraform-vault#13]
Running `jx project quickstart` fails for self managed worker nodes:
```
rpc error: code = Unknown desc = Error: No such container: 6ace51a717829ce2ea28612dace2b1c084908ce80b282f5a4c4bc498ff9c1128
panic: runtime error: index out of range [3] with length 0

goroutine 31 [running]:
github.com/jenkins-x/jx/v2/pkg/logs.hasStepFailed(0xc000ff3800, 0x3, 0x3484120, 0xc00044c3c0, 0xc000bf3c4a, 0x2, 0x0)
	/go/pkg/mod/github.com/jenkins-x/jx/v2@v2.1.121/pkg/logs/tekton_logging.go:395 +0x196
github.com/jenkins-x/jx/v2/pkg/logs.(*TektonLogger).getContainerLogsFromPod(0xc000e79e60, 0xc0009c0c00, 0xc000e15500, 0xc00088f560, 0x2a, 0xc000c5a955, 0x9, 0xc000435200, 0x1, 0x0)
	/go/pkg/mod/github.com/jenkins-x/jx/v2@v2.1.121/pkg/logs/tekton_logging.go:345 +0x719
github.com/jenkins-x/jx/v2/pkg/logs.TektonLogger.getRunningBuildLogs(0x33ba680, 0xc000a4a0a0, 0x33ec740, 0xc000b1ce80, 0x3484120, 0xc00044c3c0, 0xc0006bbfe4, 0x2, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/jenkins-x/jx/v2@v2.1.121/pkg/logs/tekton_logging.go:298 +0x6ff
github.com/jenkins-x/jx/v2/pkg/logs.(*TektonLogger).GetRunningBuildLogs.func1(0xc000435200, 0xc000aee380, 0xc000e15500, 0xc00088f560, 0x2a, 0x27f3700)
	/go/pkg/mod/github.com/jenkins-x/jx/v2@v2.1.121/pkg/logs/tekton_logging.go:221 +0x120
created by github.com/jenkins-x/jx/v2/pkg/logs.(*TektonLogger).GetRunningBuildLogs
	/go/pkg/mod/github.com/jenkins-x/jx/v2@v2.1.121/pkg/logs/tekton_logging.go:219 +0x8d
```
This does not happen for eks managed node groups. In both cases, the cluster version is 1.17.

**Comment by ankitm123** [comment]
The issue is because the default ebs disk size is only 10 GB for self managed worker nodes, but 50 GB for eks node groups. While pulling the jx related images, the disks run out of space consistently.
